# Project information
site_name: 'rhincodon.biz'
site_description: 'rhincodon.biz'
site_author: 'kota@rhincodon.org'

# Copyright
copyright: 'Copyright (c) 2018 rhincodon.org'

# Repo
repo_name: 'rhincodon-org/rhincodon.biz'
repo_url: 'https://github.com/rhincodon-org/rhincodon.biz'
edit_uri: ""

# Documentation and theme
docs_dir: 'docs'
theme: 
  name: 'material'
  language: 'en'
  palette:
    primary: 'Green'
    accent: 'Green'
  logo:
    icon: 'shared'
  feature:
    tabs: true
#  direction: 'ltr'

# Options
extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  social:
    - type: 'github'
      link: 'https://github.com/rhincodon-org'
    - type: 'twitter'
      link: 'https://twitter.com/rhincodon_org'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - plantuml